apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtest
  template:
    metadata:
      labels:
        app: loadtest
    spec:
      containers:
        - name: loadtest
          image: perfana/maven-gatling-loadtest:0.0.2
          volumeMounts:
            - mountPath: /loadtest/src
              name: loadtest-dir
              subPath: src
            - mountPath: /loadtest/pom.xml
              name: pom-xml-file
              subPath: pom.xml
      initContainers:
        - name: unpack-loadtest-tar
          image: alpine:3.18
          command:
            - sh
            - -c
          args:
            - echo Unpacking loadtest tar;
              tar -xzf /tar/loadtest-gatling.tar.gz --strip-components=1 -C /loadtest/src;
              echo Finished unpacking loadtest tar;
          volumeMounts:
            - mountPath: /loadtest/src
              name: loadtest-dir
            - mountPath: /tar
              name: unpack-loadtest-tar
      volumes:
        - name: loadtest-dir
          emptyDir: {}
        - name: unpack-loadtest-tar
          configMap:
            name: loadtest-gatling.tar.gz
        - name: pom-xml-file
          configMap:
            name: pom.xml
